### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by stevehoover** [os-fpga/Virtual-FPGA-Lab#7]
URLs for examples should use the `code_url` parameter to reference examples to load. For example, this opens WARP-V: http://www.makerchip.com/sandbox?code_url=https:%2F%2Fraw.githubusercontent.com%2Fstevehoover%2Fwarp-v%2Fmaster%2Fwarp-v.tlv

**Comment by BalaDhinesh** [comment]
Updated
